/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libraryApp;

import javax.swing.*;
import java.sql.*;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

public class BookAdd extends javax.swing.JFrame {

    Connection connection;
    public BookAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_BookName = new javax.swing.JTextField();
        text_WriterName = new javax.swing.JTextField();
        text_BookContent = new javax.swing.JTextField();
        button_Save = new javax.swing.JButton();
        button_Back = new javax.swing.JButton();
        button_Exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KİTAP EKLEME EKRANI");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("KİTABIN ADI");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 160, 110, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("KİTAP YAZARI");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 240, 110, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("KİTAP İÇERİĞİ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 320, 110, 50);

        text_BookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_BookNameActionPerformed(evt);
            }
        });
        getContentPane().add(text_BookName);
        text_BookName.setBounds(240, 160, 380, 50);
        getContentPane().add(text_WriterName);
        text_WriterName.setBounds(240, 240, 380, 50);
        getContentPane().add(text_BookContent);
        text_BookContent.setBounds(240, 320, 380, 50);

        button_Save.setBackground(new java.awt.Color(153, 153, 153));
        button_Save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tamam.png"))); // NOI18N
        button_Save.setText("ONAYLA");
        button_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SaveActionPerformed(evt);
            }
        });
        getContentPane().add(button_Save);
        button_Save.setBounds(300, 420, 130, 50);

        button_Back.setBackground(new java.awt.Color(153, 153, 153));
        button_Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Back.setText("<- GERİ");
        button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_BackActionPerformed(evt);
            }
        });
        getContentPane().add(button_Back);
        button_Back.setBounds(10, 620, 90, 40);

        button_Exit.setBackground(new java.awt.Color(153, 153, 153));
        button_Exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Exit.setText("ÇIKIŞ");
        button_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ExitActionPerformed(evt);
            }
        });
        getContentPane().add(button_Exit);
        button_Exit.setBounds(930, 620, 90, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("KİTAP EKLEME EKRANI");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 60, 610, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/kitaplikAyarlarıEkranı.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1030, 700);

        setSize(new java.awt.Dimension(1040, 708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SaveActionPerformed
       

        try{
         Db_Helper db = new Db_Helper();
        connection = db.getConnection();
        Statement statement = connection.createStatement();    
            
            
        String bookName = text_BookName.getText();
        String bookWriter = text_WriterName.getText();
        String bookContent = text_BookContent.getText();
        String sql = "INSERT INTO kitaplar VALUES('" + bookName + "' , '" + bookWriter + "' , '"+ bookContent +"')";

        if (text_BookName.getText().equals("") || text_WriterName.getText().equals("") || text_BookContent.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "KUTUCUKLAR BOŞ BIRAKILAMAZ");
        } else {
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "KİTAP KAYIT ETME İŞLEMİ BAŞARILI");
            text_BookName.setText("");
            text_WriterName.setText("");
            text_BookContent.setText("");
        }
        }
        catch(SQLException ex){
            
        }
    }//GEN-LAST:event_button_SaveActionPerformed

    private void text_BookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_BookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_BookNameActionPerformed

    private void button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_BackActionPerformed
       PageBooks menu;
        try {
            menu = new PageBooks();
            menu.setVisible(true);
            setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(BookAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_button_BackActionPerformed

    private void button_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ExitActionPerformed
        setVisible(false);
    }//GEN-LAST:event_button_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Back;
    private javax.swing.JButton button_Exit;
    private javax.swing.JButton button_Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField text_BookContent;
    private javax.swing.JTextField text_BookName;
    private javax.swing.JTextField text_WriterName;
    // End of variables declaration//GEN-END:variables
}
