/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libraryApp;

import java.sql.*;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class LoginScreen extends javax.swing.JFrame {

    public static String ad;
    Connection connection;
    PreparedStatement pst;
    ResultSet rs;
    String sifre;
    String yetki;
    
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_UserName = new javax.swing.JTextField();
        button_Login = new javax.swing.JButton();
        button_Register = new javax.swing.JButton();
        button_Exit = new javax.swing.JButton();
        text_Password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/kullanıcıı.png"))); // NOI18N
        jLabel1.setText("KULLANICI ADI");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 120, 160, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/kilit.png"))); // NOI18N
        jLabel2.setText("   ŞİFRE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 170, 80, 37);
        getContentPane().add(text_UserName);
        text_UserName.setBounds(640, 120, 280, 32);

        button_Login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tamam.png"))); // NOI18N
        button_Login.setText("GİRİŞ");
        button_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(button_Login);
        button_Login.setBounds(640, 230, 120, 50);

        button_Register.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ekle.png"))); // NOI18N
        button_Register.setText("KAYIT OL");
        button_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(button_Register);
        button_Register.setBounds(800, 230, 120, 50);

        button_Exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/programkapat.png"))); // NOI18N
        button_Exit.setText("KAPAT");
        button_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ExitActionPerformed(evt);
            }
        });
        getContentPane().add(button_Exit);
        button_Exit.setBounds(910, 610, 110, 30);

        text_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(text_Password);
        text_Password.setBounds(640, 170, 280, 37);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("GİRİŞ EKRANI");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(590, 50, 350, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Login.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 10, 1030, 700);

        setSize(new java.awt.Dimension(1040, 708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_LoginActionPerformed
       try {
            Db_Helper db = new Db_Helper();
            connection = db.getConnection();
            String sql = "Select * FROM kullanici";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            boolean kont = true;
            while (rs.next() && kont) {
                ad = rs.getString("Kullanici_Adi");
                sifre = rs.getString("Kullanici_Sifre");
                yetki=rs.getString("Yetki");
                if(text_UserName.getText().equals("")|| text_Password.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "KULLANICI ADI VE ŞİFRE ALANI BOŞ BIRAKILAMAZ");
                    kont=false;
                } else if (ad.equals(text_UserName.getText())&& sifre.equals(text_Password.getText()) && yetki.equals("1")){
                    JOptionPane.showMessageDialog(null, "YÖNETİCİ GİRİŞİ BAŞARILI");
                    AdminLogin menu=new AdminLogin();
                    menu.setVisible(true);
                    setVisible(false);
                    kont=false;
                } else if (ad.equals(text_UserName.getText())&& sifre.equals(text_Password.getText()) && yetki.equals("0")) {
                    JOptionPane.showMessageDialog(null, "KULLANICI GİRİŞİ BAŞARILI");
                    UserLogin menu=new UserLogin();
                    menu.setVisible(true);
                    setVisible(false);
                    kont=false;
                    
                }                
            }
            if (kont){
                JOptionPane.showMessageDialog(null, "SİSTEMDE KAYITLI KULLANICI  BULUNAMADI");
                text_UserName.setText("");
                text_Password.setText("");
            }
        } catch (SQLException exception) {}
    }//GEN-LAST:event_button_LoginActionPerformed

    private void button_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_RegisterActionPerformed
       try{
        Db_Helper db = new Db_Helper();
        connection = db.getConnection();
        Statement statement;
        statement = connection.createStatement();
        ad = text_UserName.getText();
        sifre = text_Password.getText();
        String sql = "INSERT INTO kullanici VALUES('" + ad + "' , '" + sifre + "' , 0)";
        statement.executeUpdate(sql);
        JOptionPane.showMessageDialog(null, "KULLANICI KAYIT ETME İŞLEMİ BAŞARILI");
        text_UserName.setText("");
        text_Password.setText("");
       }
       catch(SQLException ex){
           
       }
    }//GEN-LAST:event_button_RegisterActionPerformed

    private void button_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ExitActionPerformed
           setVisible(false);
    }//GEN-LAST:event_button_ExitActionPerformed

    private void text_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Exit;
    private javax.swing.JButton button_Login;
    private javax.swing.JButton button_Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField text_Password;
    private javax.swing.JTextField text_UserName;
    // End of variables declaration//GEN-END:variables
}
