/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libraryApp;

import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static libraryApp.Db_Helper.db_URL;
import static libraryApp.Db_Helper.password;
import static libraryApp.Db_Helper.username;

public class PageUser extends javax.swing.JFrame {

    public static String userId;
    Connection conn = DriverManager.getConnection(db_URL, username, password);
    Statement st = conn.createStatement();
    String sqld = "SELECT * FROM kullanici";
    ResultSet rs = st.executeQuery(sqld);
    public PageUser() throws SQLException{
        initComponents();
        DefaultTableModel tblModel = (DefaultTableModel) table_User.getModel();
        Db_Helper.dbToTableKullanici(tblModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_Name = new javax.swing.JTextField();
        text_Password = new javax.swing.JTextField();
        button_Remove = new javax.swing.JButton();
        button_Back = new javax.swing.JButton();
        button_Edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_User = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ÜYE AYARLARI");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("KULLANICI ADI");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 100, 130, 31);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("ŞİFRE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 150, 53, 31);
        getContentPane().add(text_Name);
        text_Name.setBounds(330, 100, 480, 31);
        getContentPane().add(text_Password);
        text_Password.setBounds(330, 150, 480, 31);

        button_Remove.setBackground(new java.awt.Color(153, 153, 153));
        button_Remove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/programkapat.png"))); // NOI18N
        button_Remove.setText("SİL");
        button_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_RemoveActionPerformed(evt);
            }
        });
        getContentPane().add(button_Remove);
        button_Remove.setBounds(180, 190, 240, 40);

        button_Back.setBackground(new java.awt.Color(153, 153, 153));
        button_Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Back.setText("<- GERİ");
        button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_BackActionPerformed(evt);
            }
        });
        getContentPane().add(button_Back);
        button_Back.setBounds(40, 600, 90, 40);

        button_Edit.setBackground(new java.awt.Color(153, 153, 153));
        button_Edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Edit.setText("DÜZENLE");
        button_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_EditActionPerformed(evt);
            }
        });
        getContentPane().add(button_Edit);
        button_Edit.setBounds(580, 190, 230, 40);

        table_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KULLANICI ADI", "ŞİFRESİ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_UserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_User);
        if (table_User.getColumnModel().getColumnCount() > 0) {
            table_User.getColumnModel().getColumn(0).setResizable(false);
            table_User.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 250, 860, 340);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("ÜYE AYARLARI");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 30, 500, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1020, 700);

        setSize(new java.awt.Dimension(1040, 708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_UserMouseClicked
       DefaultTableModel model =(DefaultTableModel)table_User.getModel();
        int selectrowindex = table_User.getSelectedRow();
        userId = model.getValueAt(selectrowindex, 0).toString();
        text_Name.setText(model.getValueAt(selectrowindex, 0).toString());
        text_Password.setText(model.getValueAt(selectrowindex, 1).toString());
    }//GEN-LAST:event_table_UserMouseClicked

    private void button_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_RemoveActionPerformed
         DefaultTableModel model = (DefaultTableModel) table_User.getModel();
        int selectrowindex = table_User.getSelectedRow();
        String userName = model.getValueAt(selectrowindex, 0).toString();
        try {
            Db_Helper.DeleteUser(userName);
            PageUser menu = new PageUser();
            menu.setVisible(true);
        setVisible(false);
        } catch (SQLException ex) {}

        
    }//GEN-LAST:event_button_RemoveActionPerformed

    private void button_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_EditActionPerformed
      String userName = text_Name.getText();
            String userPassword = text_Password.getText();
            try {
                Db_Helper.UpdateUser(userName, userPassword, userId);
                 PageUser menu = new PageUser();
                 menu.setVisible(true);
                 setVisible(false);
            } catch (SQLException e) {}

           
    }//GEN-LAST:event_button_EditActionPerformed

    private void button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_BackActionPerformed
        AdminLogin menu=new AdminLogin();
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_button_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PageUser().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PageUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Back;
    private javax.swing.JButton button_Edit;
    private javax.swing.JButton button_Remove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_User;
    private javax.swing.JTextField text_Name;
    private javax.swing.JTextField text_Password;
    // End of variables declaration//GEN-END:variables
}
