/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libraryApp;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import static libraryApp.Db_Helper.db_URL;
import static libraryApp.Db_Helper.password;
import static libraryApp.Db_Helper.username;

public class PageBooks extends javax.swing.JFrame {

    Connection conn = DriverManager.getConnection(db_URL, username, password);
    Statement st = conn.createStatement();
    String sqld = "SELECT * FROM kitaplar";
    ResultSet rs = st.executeQuery(sqld);
    public PageBooks() throws SQLException{
        initComponents();
        DefaultTableModel tblModel = (DefaultTableModel) table_Books.getModel();
        Db_Helper.dbToTable(tblModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_Remove = new javax.swing.JButton();
        button_Edit = new javax.swing.JButton();
        button_Add = new javax.swing.JButton();
        button_Back = new javax.swing.JButton();
        button_Exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Books = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        button_Remove.setBackground(new java.awt.Color(153, 153, 153));
        button_Remove.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        button_Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/programkapat.png"))); // NOI18N
        button_Remove.setText("SİL");
        button_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_RemoveActionPerformed(evt);
            }
        });
        getContentPane().add(button_Remove);
        button_Remove.setBounds(70, 80, 200, 50);

        button_Edit.setBackground(new java.awt.Color(153, 153, 153));
        button_Edit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        button_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ekle.png"))); // NOI18N
        button_Edit.setText("DÜZENLE");
        button_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_EditActionPerformed(evt);
            }
        });
        getContentPane().add(button_Edit);
        button_Edit.setBounds(400, 80, 200, 50);

        button_Add.setBackground(new java.awt.Color(153, 153, 153));
        button_Add.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        button_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tamam.png"))); // NOI18N
        button_Add.setText("EKLE");
        button_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AddActionPerformed(evt);
            }
        });
        getContentPane().add(button_Add);
        button_Add.setBounds(740, 80, 200, 50);

        button_Back.setBackground(new java.awt.Color(153, 153, 153));
        button_Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Back.setText("<- GERİ");
        button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_BackActionPerformed(evt);
            }
        });
        getContentPane().add(button_Back);
        button_Back.setBounds(20, 560, 90, 30);

        button_Exit.setBackground(new java.awt.Color(153, 153, 153));
        button_Exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/programkapat.png"))); // NOI18N
        button_Exit.setText("ÇIKIŞ");
        button_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ExitActionPerformed(evt);
            }
        });
        getContentPane().add(button_Exit);
        button_Exit.setBounds(900, 560, 90, 31);

        table_Books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "KŞTAP İSMİ", "YAZARI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_Books);
        if (table_Books.getColumnModel().getColumnCount() > 0) {
            table_Books.getColumnModel().getColumn(0).setResizable(false);
            table_Books.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(72, 147, 870, 402);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("KİTAP AYARLARI ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 20, 440, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1020, 700);

        setSize(new java.awt.Dimension(1040, 708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_RemoveActionPerformed
       
        try {
             DefaultTableModel model = (DefaultTableModel) table_Books.getModel();
             int selectrowindex = table_Books.getSelectedRow();
             String bookName = model.getValueAt(selectrowindex, 0).toString();
            
            Db_Helper.DeleteBooks(bookName);
             PageBooks menu = new PageBooks();
             menu.setVisible(true);
             setVisible(false);
        } catch (SQLException ex) {}
        
    }//GEN-LAST:event_button_RemoveActionPerformed

    private void button_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_EditActionPerformed
        BookEdit menu;
        try {
            menu = new BookEdit();
            menu.setVisible(true);
            setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(PageBooks.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_button_EditActionPerformed

    private void button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_BackActionPerformed
        AdminLogin menu=new AdminLogin();
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_button_BackActionPerformed

    private void button_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ExitActionPerformed
      setVisible(false);
    }//GEN-LAST:event_button_ExitActionPerformed

    private void button_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AddActionPerformed
        BookAdd menu=new BookAdd();
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_button_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PageBooks().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PageBooks.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Add;
    private javax.swing.JButton button_Back;
    private javax.swing.JButton button_Edit;
    private javax.swing.JButton button_Exit;
    private javax.swing.JButton button_Remove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_Books;
    // End of variables declaration//GEN-END:variables
}
