/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libraryApp;


import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.*;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import static libraryApp.Db_Helper.db_URL;
import static libraryApp.Db_Helper.password;
import static libraryApp.Db_Helper.username;
import static libraryApp.LoginScreen.ad;


public class UserLogin extends javax.swing.JFrame {

    Connection connection;
    PreparedStatement pst;
    Connection conn = DriverManager.getConnection(db_URL, username, password);
    Statement st = conn.createStatement();
    String sqld = "SELECT * FROM kitaplar";
    ResultSet rs = st.executeQuery(sqld);
    public UserLogin() throws SQLException{
        System.out.println(ad);
        
        initComponents();
        DefaultTableModel tblModel = (DefaultTableModel) table_Books.getModel();
        Db_Helper.dbToTable(tblModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_Books = new javax.swing.JTable();
        button_Download = new javax.swing.JButton();
        button_Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        table_Books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KİTAP İSMİ", "YAZARI", "İÇERİGİ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_Books);
        if (table_Books.getColumnModel().getColumnCount() > 0) {
            table_Books.getColumnModel().getColumn(0).setResizable(false);
            table_Books.getColumnModel().getColumn(1).setResizable(false);
            table_Books.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(69, 185, 870, 337);

        button_Download.setBackground(new java.awt.Color(153, 153, 153));
        button_Download.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        button_Download.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ekle.png"))); // NOI18N
        button_Download.setText("KİTAP İNDİR");
        button_Download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DownloadActionPerformed(evt);
            }
        });
        getContentPane().add(button_Download);
        button_Download.setBounds(350, 80, 330, 70);

        button_Back.setBackground(new java.awt.Color(153, 153, 153));
        button_Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Back.setText("<- GERİ");
        button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_BackActionPerformed(evt);
            }
        });
        getContentPane().add(button_Back);
        button_Back.setBounds(40, 550, 100, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("ÜYE KİTAP İNDİRME EKRANI");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 10, 690, 60);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setText("LÜTFEN İNDİRMEK İSTEDİĞİNİZ KİTABI TABLODA İŞARETLEYEREK İNDİR BUTONUNA TIKLAYINIZ ....");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 160, 530, 16);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/KullaniciArkaPlan.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 700);

        setSize(new java.awt.Dimension(1040, 708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_DownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_DownloadActionPerformed
       try{
           DefaultTableModel model =(DefaultTableModel)table_Books.getModel();
        int selectrowindex= table_Books.getSelectedRow();
        String kitapAdi = model.getValueAt(selectrowindex, 0).toString();

        Db_Helper db = new Db_Helper();
        connection = db.getConnection();
        String sql = "Select * FROM kitaplar";
        pst = connection.prepareStatement(sql);
        rs = pst.executeQuery();

        while (rs.next()) {
            if(kitapAdi.equals(rs.getString("Kitap_Adi"))) {

                String kitap = rs.getString("Kitap_Adi");
                String yazar = rs.getString("Kitap_Yazari");
                String sayfalar = rs.getString("Kitap_İcerigi");
                String DATA;
                String dosyaYolu = "C:\\Users\\Pc\\Desktop\\" + ad;
                File myFile = new File(dosyaYolu);
                myFile.mkdir();
                myFile.createNewFile();

                dosyaYolu = dosyaYolu + "\\" + kitap +".rtf";
                DATA = "Yazar Adı: " + yazar + "\n\n" + sayfalar;
                File dosya = new File(dosyaYolu);
                FileWriter yazici = new FileWriter(dosya);
                BufferedWriter yaz = new BufferedWriter(yazici);
                yaz.write(DATA);
                yaz.close();
                JOptionPane.showMessageDialog(rootPane, "KİTAP BAŞARILI BİR ŞEKİLDE İNDİRİLDİ");
            }
            
        }
       }
       catch(SQLException ex){
           
       } catch (IOException ex) {
            Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_DownloadActionPerformed

    private void button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_BackActionPerformed
       LoginScreen menu=new LoginScreen();
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_button_BackActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserLogin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Back;
    private javax.swing.JButton button_Download;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_Books;
    // End of variables declaration//GEN-END:variables
}
